version: "3"

services:
  postgresql:
    build:
      dockerfile: Dockerfile
    container_name: "soa-postgresql"
    image: postgres:15.5
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_MULTIPLE_DATABASES: social_media, post_service
    ports:
      - "5432:5432"
    networks:
      - soa-network
    volumes:
      - ./configs/create-multiple-db-with-users.sh:/docker-entrypoint-initdb.d/create-multiple-db-with-users.sh:ro
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 10s
      timeout: 5s
      retries: 5

  liquibase-migrations-user:
    image: liquibase/liquibase:4.19.0
    networks:
      - soa-network
    depends_on:
      - postgresql
    volumes:
      - ../../social-media/migrations:/app
    command: --defaultsFile=/app/dev.properties update

  liquibase-migrations-post:
    image: liquibase/liquibase:4.19.0
    networks:
      - soa-network
    depends_on:
      - postgresql
    volumes:
      - ../../post-service/migrations:/app
    command: --defaultsFile=/app/dev.properties update

  pgadmin:
    container_name: "soa-pgadmin"
    image: dpage/pgadmin4
    restart: unless-stopped
    entrypoint: >
      /bin/sh -c "
      cp -f /pgadmin4/pgpass /var/lib/pgadmin/;
      chmod 600 /var/lib/pgadmin/pgpass;
      /entrypoint.sh
      "
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "8080:80"
    networks:
      - soa-network
    volumes:
      - ./configs/servers.json:/pgadmin4/servers.json:ro
      - ./configs/pgpass:/pgadmin4/pgpass:ro

  social-media:
    container_name: "social-media"
    image: social-media
    restart: unless-stopped
    ports:
      - "0.0.0.0:8000:8000"
    build:
      context: ../../
      dockerfile: social-media/src/Dockerfile
    networks:
      - soa-network
  post-service:
    container_name: "post-service"
    image: post-service
    restart: unless-stopped
    ports:
      - "0.0.0.0:8001:8001"
    build:
      context: ../../
      dockerfile: post-service/src/Dockerfile
    networks:
      - soa-network

networks:
  soa-network:
    name: "soa-network"