@startuml
!include <C4/C4_Container>

Person(person, "Пользователь", "Пользователь социальной сети")

System(social_media, "ЛК пользователя", "Социальная сеть")

Rel(person, social_media, "Регистрация/аутентификация пользователя, \
обновление/удаление постов, получение своей стены с постами, \
просмотр стен других пользователей")

@enduml